quarkus.shutdown.timeout=30s

## ==========================
## For local Kafka service
## ==========================
#kafka.bootstrap.servers=localhost:9092
#kafka.security.protocol=PLAINTEXT

## ==========================
## For custom worker pool
## You need to uncomment @Blocking(value = "my-custom-pool") in CounterConsumer class
## ==========================
#smallrye.messaging.worker.my-custom-pool.max-concurrency=2
#smallrye.messaging.worker.my-custom-pool.shutdown-timeout=5000
#smallrye.messaging.worker.my-custom-pool.shutdown-check-interval=1000

## ==========================
## Incoming channel
## ==========================
mp.messaging.incoming.counter.connector=smallrye-kafka
mp.messaging.incoming.counter.topic=mycounter
mp.messaging.incoming.counter.group.id=test-group
mp.messaging.incoming.counter.pausable=true
mp.messaging.incoming.counter.graceful-shutdown-timeout = 5s

## ==========================
## Outgoing channel
## ==========================
mp.messaging.outgoing.counter-out.connector=smallrye-kafka
mp.messaging.outgoing.counter-out.topic=mycounter
mp.messaging.outgoing.counter-out.group.id=test-group